### ISSUE TITLE
Some questions about vm box!

### ISSUE THREAD

**Issue by bigbigbanana** [KVM-VMI/kvm-vmi#10]
@Wenzel 
Hello,according to your guidances,i went to the vagrant/ sub-directory to install a development environment for kvm-vmi,i downloaded a box file from http://www.vagrantbox.es/ and unzip it to get a win7_x64.box file.But when i run vagrant up --provider=libvirt,i got the following results,i guess the mirror image may not be right,so i want to know how can i create a win7 test vm and run it?
![2017-07-05 15-00-20](https://user-images.githubusercontent.com/24928429/27853546-aa0ab4a2-6195-11e7-839e-f32acef23939.png)

**Comment by Wenzel** [comment]
Hi @bigbigbanana ,

you don't need to manually download a vagrant box, vagrant will do that for up when you run `vagrant up --provider=libvirt`.

Why are you trying to download a win7 vagrant box ?

vagrant is used to provision a development environement, which is a linux box, on top of which a win7 VM will be depoyed by the ansible playbook.

Just follow the instructions and tune the Vagrantfile to your needs, but don't change the box. `config.vm.box = "debian/jessie64"`

You should read a bit further what [Vagrant](https://www.vagrantup.com/) is.

**Comment by bigbigbanana** [comment]
@Wenzel 
First,i am very grateful for your help，when i run vagrant up --provider=libvirt and vagrant reload,i got the following results,how can i fix it?
![2017-07-05 16-01-39](https://user-images.githubusercontent.com/24928429/27855118-e2ce6346-619b-11e7-97e8-1c0824612805.png)

**Comment by Wenzel** [comment]
Seems like a vagrant related issue to me.
Do you have the latest version ? `vagrant status` ?
i haven't used it for a while.
Try to post your issue on the vagrant repo.

**Comment by bigbigbanana** [comment]
Here is the version of vagrant,vagrant plugin and libvirtd,i just post my issue on vagrant-libvirt repo.Thanks!
![2017-07-05 16-26-43](https://user-images.githubusercontent.com/24928429/27856145-abdca0e2-619f-11e7-95d5-98d8ef9b4464.png)

**Comment by bigbigbanana** [comment]
@Wenzel 
Hello,when i run  vagrant up --provider=libvirt,i got the following error and when i run this command again,it seems to be right,but vagrant reload still have problem,what's wrong with it?
![2017-07-12 10-42-58](https://user-images.githubusercontent.com/24928429/28099482-69482b48-66ef-11e7-8b73-8d4be60c1e8f.png)

**Comment by Wenzel** [comment]
Read the error messages.
The first one tells you that your command failed, and you need to find out why.
There is no need to run vagrant reload after that.

I never had this `domaintype=kvm` error before.
try to google it or post an issue on Vagrant repo.

**Comment by bigbigbanana** [comment]
@Wenzel 
Hello,i still couldn't fix my problem,i want to know if it's necessary to use vagrant,can i directly use virt-manager to create win7 vm?

**Comment by Wenzel** [comment]
Hi,

Vagrant is only here to help you create a ready to use dev environement.
Yes, you can create the win7 VM and import it in virt-manager.

But i wrote some scripts to help you do that.
Please check nitro/tests/vm_templates/README.md.

And if you don't use Vagrant, you will have to install kvm, qemu, libvmi and nitro by yourself ;)

**Comment by bigbigbanana** [comment]
@Wenzel 
Hi,
When i run vagrant reload,i got the following results,is this correct?Then what should i do?
![2017-07-16 17-18-41](https://user-images.githubusercontent.com/24928429/28246383-47a5c9be-6a4b-11e7-8926-2f5d02923d52.png)

**Comment by Wenzel** [comment]
Why did you cancelled the vagrant up command ?
Please, read vagrant documentation first and try to understand what i does and how it works.
i'm can't provide support for vagrant issues unfortunately.

**Comment by bigbigbanana** [comment]
@Wenzel 
Hi,i successfully use vagrant ssh to ssh into the box,but i don't know how to create and start the test vm nitro_win7x64,when i use virt-manager,it shows the following result.
![2017-09-01 08_36_17](https://user-images.githubusercontent.com/24928429/29951285-4778aefc-8ef4-11e7-8677-a41a6f5700ab.png)

**Comment by Wenzel** [comment]
It's written in the README:

- Start the test vm with virsh start nitro_win7x64 (or use virt-manager connection).

The VM has already been created by the ansible playbook.
You just have to start it using virsh:
`$ virsh start nitro_win7x64`, in the vagrant ssh shell.

Or use `virt-manager` and add a new connection.

Please look at the README for the details.

**Comment by bigbigbanana** [comment]
@Wenzel 
Hello,Wenzel,i want to trace system calls under Xen,if you know some other projects doing the same job recently,please tell me.Thanks very much.

**Comment by Wenzel** [comment]
Hi, take a look at Drakvuf : https://drakvuf.com/

If i answered your questions about the vm box (title of the issue) please close this ticket.
