### ISSUE TITLE
Bitdefender KVM patches posted

### ISSUE THREAD

**Issue by tklengyel** [KVM-VMI/kvm-vmi#11]
I guess if they get the ball rolling we should chime in as well, if for nothing else, to show that the interface is indeed needed ;)

https://www.spinics.net/lists/kvm/msg151508.html

**Comment by tklengyel** [comment]
v2 is out too

http://www.spinics.net/lists/kvm/msg152567.html

**Comment by noxdafox** [comment]
Hi @tklengyel, we are aware of those patches. We are evaluating how to proceed with them.
