### ISSUE TITLE
Vagrant up error

### ISSUE THREAD

**Issue by yqLee-xd** [KVM-VMI/kvm-vmi#110]
I‘ve got this error when I run vagrant up --provider libvirt:

> > TASK [run kvm self-tests] ******************************************************
> fatal: [kvmi]: FAILED! => changed=true 
>   cmd:
>   - ./tools/testing/selftests/kvm/x86_64/kvmi_test
>   delta: '0:00:00.002579'
>   end: '2021-07-23 08:42:28.008696'
>   msg: non-zero return code
>   rc: 4
>   start: '2021-07-23 08:42:28.006117'
>   stderr: ''
>   stderr_lines: []
>   stdout: ''
>   stdout_lines: <omitted>
> 	to retry, use: --limit @/vagrant/vagrant/ansible/playbook_2.retry
> 
> PLAY RECAP *********************************************************************
> kvmi                       : ok=5    changed=3    unreachable=0    failed=1   
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.
>

**Comment by Wenzel** [comment]
Hi  @yqLee-xd , thanks for reporting an issue.

Are you running on an AMD CPU ?

if the box hasn't been destroyed yet (vagrant destroys the box on error, unless you specify `--no-destroy-on-error`), you should be able to `vagrant ssh` into the VM and run the self-tests again, to get more meaningful output.

**Comment by yqLee-xd** [comment]
> Hi @yqLee-xd , thanks for reporting an issue.
> 
> Are you running on an AMD CPU ?
> 
> if the box hasn't been destroyed yet (vagrant destroys the box on error, unless you specify `--no-destroy-on-error`), you should be able to `vagrant ssh` into the VM and run the self-tests again, to get more meaningful output.

In fact, I used a virtual machine(VMware) and opened VT-x. The CPU of my underlying hardware is Intel's Core i7.
That’s the first time I use Vagrant.I’ll try the method you provided.

**Comment by Wenzel** [comment]
@yqLee-xd you can simply disable (comment) the kvm self-tests in the ansible playbook if you cannot find a workaround.

**Comment by yqLee-xd** [comment]
> @yqLee-xd you can simply disable (comment) the kvm self-tests in the ansible playbook if you cannot find a workaround.

I saw related replies to previous posts, but I don’t know how to disable (comment) the kvm self-tests in the ansible playbook.=_=
A little embarrassing for me.==

**Comment by Wenzel** [comment]
Actually, a simpler solution would be to update the Ansible tasks so that any error is ignored:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#ignoring-failed-commands

https://github.com/KVM-VMI/kvm-vmi/blob/master/vagrant/ansible/playbook_2.yml
~~~YAML
    - name: run kvm self-tests
      command: ./tools/testing/selftests/kvm/x86_64/kvmi_test
      args:
        chdir: "{{ root_dir }}/kvm"
      ignore_errors: yes
~~~

**Comment by yqLee-xd** [comment]
> Actually, a simpler solution would be to update the Ansible tasks so that any error is ignored:
> https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#ignoring-failed-commands
> 
> https://github.com/KVM-VMI/kvm-vmi/blob/master/vagrant/ansible/playbook_2.yml
> 
> ```yaml
>     - name: run kvm self-tests
>       command: ./tools/testing/selftests/kvm/x86_64/kvmi_test
>       args:
>         chdir: "{{ root_dir }}/kvm"
>       ignore_errors: yes
> ```

OK！It‘s work！The following steps are in progress. Thanks a lot Mr.Wenzel.

**Comment by Wenzel** [comment]
Awesome, my pleasure !
Don't forget to join the Slack community to continue the discussion:
https://kvm-vmi.herokuapp.com/

**Comment by Wenzel** [comment]
Closing this issue
