### ISSUE TITLE
How to identify a guest PID?

### ISSUE THREAD

**Issue by threeearcat** [KVM-VMI/kvm-vmi#12]
Hi.

In my project, I need that qemu identify a guest PID when some events occur in a kernel.
What I'm thinking is reading registers (cr3, kernel's rsp, ...), identifying the pid's address and reading pid from guest memory.
Could you let me know how nitro identify a guest PID and where it is implemented in a source code?
Thank you.

**Comment by Wenzel** [comment]
Hi @threeearcat ,

Did i answered all of your questions, or do you have more ?
Otherwise please close this issue.

Regards.

**Comment by threeearcat** [comment]
Oh, I'm sorry for the late response.
Yes, your answer is helpful and that is what I want to know
Sorry and thank you!
