### ISSUE TITLE
kernel compiled error...

### ISSUE THREAD

**Issue by Pai-Po** [KVM-VMI/kvm-vmi#124]
[master-doc](https://kvm-vmi.github.io/kvm-vmi/master/setup.html)
[kvmi-doc](https://kvm-vmi.github.io/kvm-vmi/kvmi/setup.html)
If you compiled the kernel that conforms to the document `master-doc`, you will get some errors like this.
<img width="595" alt="Screen Shot 2021-09-12 at 4 29 48 PM" src="https://user-images.githubusercontent.com/12437819/132980072-6e753b32-0eed-4e06-a012-f6c5aab3672d.png">
After several tests, I found that 'KSM' is enabled by default, and 'Remote Mapping is off by default.
If you set these two options accorded to another document `[kvmi-doc]`, then the kernel can be compiled successfully.
So, I want to know if kvmi-v 7 has supported ksm or not?

**Comment by Wenzel** [comment]
Hi @Pai-Po,

the main documentation for kvm-vmi should be from the `master` branch.
Regarding this issue, we recently merged a doc update:
https://github.com/KVM-VMI/kvm-vmi/pull/119

Which changed the requirements for KSM and REMOTE_MAPPING.
Apprently, this change had unintended consequences.

I will reflect @adlazar change in the vagrant and confirm that the kernel doesn't compile with this new configuration.
In the meantime, @adlazar , do you have any workaround / fix ?

Thank you for the bug report.

**Comment by Pai-Po** [comment]
I got your point, but I want to know if ksm had been supported?

**Comment by Wenzel** [comment]
I don't think so no. You should disable it.

**Comment by Pai-Po** [comment]
Ok, thanks
