### ISSUE TITLE
Bare-metal setup: "modules.order not found" error when running "sudo make modules_install INSTALL_MOD_STRIP=1"

### ISSUE THREAD

**Issue by PuckiPwn** [KVM-VMI/kvm-vmi#140]
Hi,
I am trying to install kvm-vmi on my Ubuntu 20.04 VM following the instructions for the bare-metal setup.

`make -j$(nproc)` runs ok, but the next command `sudo make modules_install INSTALL_MOD_STRIP=1` gives an error:

![image](https://user-images.githubusercontent.com/116574896/211210148-f0b1886a-207e-4867-9977-d6a6f48dfabb.png)

It seems like one of the commands in the makefile is looking for a file called modules.order which is not present in the current folder:

![image](https://user-images.githubusercontent.com/116574896/211209653-9745ad96-2c49-4211-abd4-c2c84dc5fc00.png)

**Comment by Wenzel** [comment]
Hi @PuckiPwn !


> I am trying to install kvm-vmi on my Ubuntu 20.04 VM following the instructions for the bare-metal setup.

If you are installing the KVM-VMI kernel inside a VM, that's not a bare-metal setup anymore, it's a nested virt setup (like Vagrant)

I just tested this command again on an Ubuntu 20.04 Docker image:
![image](https://user-images.githubusercontent.com/964610/211211152-6e21d93c-baba-4ae8-94ee-9828556ede8d.png)

I can't replicate the error that you are facing.
At least not in Docker.

**Comment by PuckiPwn** [comment]
Thank you Wenzel for the fast response! 

My host machine is running Windows 10. If I understand this correctly, if I install Docker with an Ubuntu 20,04 image this should work?

**Comment by Wenzel** [comment]
> If I understand this correctly, if I install Docker with an Ubuntu 20,04 image this should work?

Docker is a lightweight virtualization solution and not what you are looking for.
If you are running on Windows 10, please follow the Vagrant setup with the Hyper-V provider:
https://kvm-vmi.github.io/kvm-vmi/master/setup.html#windows-setup

**Comment by PuckiPwn** [comment]
Thanks for explaining,
I tried following the Vagrant Windows setup initially, but this gave me an error and therefore i tried the bare-metal setup:

![image](https://user-images.githubusercontent.com/116574896/211216477-f7b45cce-3c38-4fa4-ae97-00c5dcf944b0.png)

I can open a new issue for this , to keep things clear?

**Comment by Wenzel** [comment]
> I can open a new issue for this , to keep things clear?

Yes please !
