### ISSUE TITLE
./bootstrap not found error during Windows Vagrant setup

### ISSUE THREAD

**Issue by PuckiPwn** [KVM-VMI/kvm-vmi#143]
When running the Vagrant setup for Windows on my host (Windows 10) , I get the following error:

![image](https://user-images.githubusercontent.com/116574896/211216972-7553420c-148c-4c12-bcde-644d2ec8e5df.png)

I inspected the vagrant files and found the command executed:

![image](https://user-images.githubusercontent.com/116574896/211217046-5537e4f7-6ef9-4210-bffa-10c349581afe.png)

I then tried to do this manually by connection to the HyperV VM and executing the command resulting in an error:

![image](https://user-images.githubusercontent.com/116574896/211217095-a06baa67-24ee-4b91-b3f9-785c225e0a9b.png)

`/bin/sh^M ` indicates there is an Carriage Return character somewhere that should not be there. Following https://askubuntu.com/questions/304999/not-able-to-execute-a-sh-file-bin-bashm-bad-interpreter , I removed it using `sed` and tried running `./bootstrap` again manually, resulting in the following error:

![image](https://user-images.githubusercontent.com/116574896/211217227-b1e95bc5-1b19-4d7d-96f3-3370ab9acca6.png)

This is as far as I could get the error debugged. Not sure what to do next.

**Comment by Wenzel** [comment]
Thanks for the detailed report.
in #142 I assumed that libkvmi wasn't cloned, since it was missing from the documentation section where we clone all other submodules except KVM.
But you have it on your filesystem.
Did you clone it manually ?

Regarding the last error, it seems to be related to Windows/Unix line endings compatbility again:
https://stackoverflow.com/a/51874066

Maybe the proper way to fix this would be to configure git to not normalize the line endings for Windows:
https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

**Comment by PuckiPwn** [comment]
No problem, thanks for helping :)

I did not clone anything by hand, just followed the setup exactly.

I removed everything (full repo and HyperV VM) and reconfigured git to force it refrain from normalizing line endings:

![image](https://user-images.githubusercontent.com/116574896/211218814-6a1eeb87-ea98-4b48-b7a2-8dcf3ce8ca44.png)

Then did a `git clone` and followed the setup instructions again:

![image](https://user-images.githubusercontent.com/116574896/211219371-9efb90e7-98f6-401f-95d3-913605f8d4a0.png)

![image](https://user-images.githubusercontent.com/116574896/211219471-a8b43144-03a8-43d4-8c98-ca944785cfa0.png)

Setup now got past the bootstrap part and is still running, so fingers crossed:

![image](https://user-images.githubusercontent.com/116574896/211222052-2d6cb963-248f-4838-9488-0d36b355ad7e.png)

**Comment by PuckiPwn** [comment]
I posted to quickly. I crashed, but this time much further into the playbook, while doing `disable singlestep test`:

![image](https://user-images.githubusercontent.com/116574896/211222173-b51bc73a-81e1-459b-8073-b35bdfdb9630.png)

**Comment by PuckiPwn** [comment]
It seems to refer to files in the /vagrant/kvm folder on the HyperVM box, but this folder is empty:

![image](https://user-images.githubusercontent.com/116574896/211222390-6401f958-0124-4124-8f58-475c37d982cf.png)

It is also empty on my host:

![image](https://user-images.githubusercontent.com/116574896/211222405-6e4090b2-11d8-4079-bfae-86ee60b92ff3.png)

**Comment by Wenzel** [comment]
The kvm folder is supposed to be empty on the host because it cannot be cloned on Windows (due to filesystem naming restrictions)

However, it is supposed to be populated during the early playbook execution in /vagrant/kvm:
https://github.com/KVM-VMI/kvm-vmi/blob/master/vagrant/ansible/roles/kvm/tasks/main.yml#L18

Can you checked that this task has been executed ?
It is conditioned by the `is_windows` variable, which is a boolean populated here in the Vagrantfile:
https://github.com/KVM-VMI/kvm-vmi/blob/master/vagrant/Vagrantfile#L126

**Comment by PuckiPwn** [comment]
I connected to the VM and ran the git command to populate the kvm folder by hand. That seemed to work just fine.

Then ran vagrant up with --provision with the playbook in verbose mode (-vvv). It shows the `is_windows` variable is correctly set to true:

![image](https://user-images.githubusercontent.com/116574896/211272403-ae3d41a6-62d3-4ebd-9941-2de55187815f.png)

When populating the kvm folder on the VM it seems like the git command is executed as 5 seperate commands (or this might be how it should look? I am not familiar enough with Ansible to tell).

![image](https://user-images.githubusercontent.com/116574896/211272745-42b30f10-64fb-49ab-b5db-a81b8971d280.png)

It again fails at the singlestep check:

![image](https://user-images.githubusercontent.com/116574896/211279982-570bdfde-dcd5-4624-bcb3-78d46034a2d8.png)

I then connect manually to the VM and confirmed KVM folder is empty and that I am able to populate it manually :

![image](https://user-images.githubusercontent.com/116574896/211280711-e7506124-6aae-4cb3-9a04-861bfcf94e80.png)

It almost seems like the folder is not populated at all or gets deleted by the playbook somewhere after the `git submodule update --init kvm` and before the singlestep check.

**Comment by PuckiPwn** [comment]
Hi @Wenzel 
I believe I have found the issue after some digging and testing.

After completing the first playbook, then VM is rebooted using `config.vm.provision "reload"` in the Vagrant file.
Part of this reboot process is syncing with the host (Rsyncing folder: /cygdrive/c/kvm-vmi/ => /vagrant)

![image](https://user-images.githubusercontent.com/116574896/211412643-796e6ce6-a0ba-4c52-b2af-349b53613c44.png)

I believe because the folder is not populated on my Windows host, I is also empty on the VM after the reload.

A possible solution could be to include `git submodule update --init kvm` in the second playbook.

**Comment by PuckiPwn** [comment]
I succesfully got the Vagrant install past the `TASK [disable singlestep test]`. The remaining install is still running.

I added the `is_windows` variable to the 2nd part of the Vagrantfile (line 140):

![image](https://user-images.githubusercontent.com/116574896/211425629-61096284-22bc-4b87-9dde-c73870e3f719.png)

And in Playbook 2 I added a `git submodule update --init kvm`:

![image](https://user-images.githubusercontent.com/116574896/211425918-7446043a-eca3-470f-b33d-3a95e1683451.png)

**Comment by PuckiPwn** [comment]
The Vagrant setup completed succesfully :)

**Comment by PuckiPwn** [comment]
Another problem is that now I have succesfully installed everything, each time I run `vagrant up`, the kvm folder on the HyperV VM is emptied again.

For now , i solved it by manually running `git submodule update --init kvm` from the /vagrant folder on the HyperV VM

**Comment by Wenzel** [comment]
Congrats for fixing the playbook and making it work on your side !

> I believe because the folder is not populated on my Windows host, it is also empty on the VM after the reload.

That rsync operation shouldn't be destructive and remove folder in the destination that aren't present on the source.
Maybe you could run vagrant with debug output and check what is the exact rsync command line to make sure `--delete` isn't there.

I unfortunately don't have a windows machine to test and validate that vagrant box.

**Comment by Wenzel** [comment]
Hey @PuckiPwn !

Thanks for the investigation effort !
It's really great that we got this confirmation.

And now we can fix it in the Vagrantfile 🙂 
Right here
https://github.com/KVM-VMI/kvm-vmi/blob/master/vagrant/Vagrantfile#L95

You could copy paste the default args, and omit `"--delete"`, while keeping the playbook unmodified:
~~~Ruby
        override.vm.synced_folder "..", root_dir,
            :type => "rsync",
            :rsync__args => ["--verbose", "--archive", "-z", "--copy-links"]
~~~

If this works, please make a PR, I'll be happy to review it !

Thanks

**Comment by PuckiPwn** [comment]
Vagrant setup now completes succesfully. I created a pull request. Thanks for the help!
