### ISSUE TITLE
set_vcpuregs not supported by kvm??

### ISSUE THREAD

**Issue by netanelc305** [KVM-VMI/kvm-vmi#146]
Hi , 

I am trying to change registers , it seems that the return value is VMI_SUCCESS ,however no changes are made to the registers.

Is it possible to set registers on KVM or is it supported only by XEN?

**Comment by adlazar** [comment]
[On the kernel side](https://github.com/KVM-VMI/kvm/blob/kvmi-v7/Documentation/virt/kvm/kvmi.rst#12-kvmi_vcpu_set_registers), the command to change registers is allowed [only during vcpu events](https://github.com/KVM-VMI/kvm/blob/cc45b7af077c4514020fd403b58b674b3b1c589e/virt/kvm/introspection/kvmi.c#L996) (e.g. breakpoint) and the changes are applied when the introspector [reply to that event](https://github.com/KVM-VMI/kvm/blob/cc45b7af077c4514020fd403b58b674b3b1c589e/virt/kvm/introspection/kvmi.c#L1009).
