### ISSUE TITLE
Vagrant up error:undefined method 'dhcp_leases'!

### ISSUE THREAD

**Issue by bigbigbanana** [KVM-VMI/kvm-vmi#16]
/home/nq/.vagrant.d/gems/2.4.2/gems/fog-libvirt-0.4.1/lib/fog/libvirt/requests/compute/dhcp_leases.rb:8:in `dhcp_leases': undefined method `dhcp_leases' for #<Libvirt::Network:0x0000000003bb8ae8> (NoMethodError)
![2017-11-14 10_47_17](https://user-images.githubusercontent.com/24928429/32764814-8d72bb22-c942-11e7-8c53-eb6ba81a4b3f.png)

**Comment by Wenzel** [comment]
This is Vagrant bug, please report it at the right place, thanks.
