### ISSUE TITLE
Broken link in setup documentation

### ISSUE THREAD

**Issue by dommi22m** [KVM-VMI/kvm-vmi#166]
Hi!

I'm currently in the process to setup kvm-vmi and stumbled over ab broken link in the setup documentation. 

Exactly under: 

> Note: If you want to use the remote memory mapping feature (and setup a VM with the introspection tool) you’ll find detailed instructions [here](https://hvmi.github.io/blog/2020/08/10/getting-started-on-kvm.html).

Maybe this could be fixed? I would actually like to use the shared-memory feature.

Thanks! 
Tommy

**Comment by Wenzel** [comment]
Hi Tommy, thanks for your interest in KVM-VMI, as well as pointing out this issue in the documentation !

The link points to the HVMI blog, which is not online anymore unfortunately.
I found a copy on Webarchive though:
https://web.archive.org/web/20220331032239/https://hvmi.github.io/blog/2020/08/10/getting-started-on-kvm.html

I'll update the docs with this link

**Comment by adlazar** [comment]
> The link points to the HVMI blog, which is not online anymore unfortunately.

That blog has been moved [here](https://bitdefender.github.io/hvmi-blog/) :(
