### ISSUE TITLE
got "kvmi need a socket path to be specified" when executing libvmi

### ISSUE THREAD

**Issue by dommi22m** [KVM-VMI/kvm-vmi#168]
Hi!
As mentioned before in #167 i'm currently on setting up kvm-vmi.
So far every step in the installation worked fine and also, i got output via  `./hookguest-libkvmi /tmp/introspector`.

But if try to test libvmi i got an error:

```
fortrace@fortrace:~/libvmi-python/pythom-kvmi/examples$ sudo python3 process-list.py windows10-template
--libkvmi path: /usr/local/lib/libkvmi.so
--Destroying KVM driver
--found KVM
LibVMI Version 0.13.0
LibVMI Driver Mode 1
--libkvmi path: /usr/local/lib/libkvmi.so
--completed driver init.
--got id from name (windows10-template --> 1)
**set image_type = windows10-template
--kvmi need a socket path to be specified
--Destroying KVM driver
Traceback (most recent call last):
  File "/home/fortrace/libvmi-python/pythom-kvmi/examples/process-list.py", line 72, in <module>
    ret = main(sys.argv)
  File "/home/fortrace/libvmi-python/pythom-kvmi/examples/process-list.py", line 18, in main
    with Libvmi(vm_name) as vmi:
  File "/usr/local/lib/python3.10/dist-packages/libvmi-3.4-py3.10-linux-x86_64.egg/libvmi/libvmi.py", line 288, in __init__
    check(status, error_msg)
  File "/usr/local/lib/python3.10/dist-packages/libvmi-3.4-py3.10-linux-x86_64.egg/libvmi/libvmi.py", line 211, in check
    raise LibvmiError(error)
libvmi.libvmi.LibvmiError: DRIVER
```

I think the problematic point is: `--kvmi need a socket path to be specified`

The VM is configured as described in the documentation and also i added two lines as i found it here: [https://github.com/KVM-VMI/kvm-vmi/issues/44#issuecomment-565695296](url)
So my config is:
```
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
  <name>windows10-template</name>
  .......
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">8192000</memory>
  <currentMemory unit="KiB">8192000</currentMemory>
  <memoryBacking>
    <source type="memfd"/>
    <access mode="shared"/>
  </memoryBacking>
  <vcpu placement="static">8</vcpu>
  <os>
    <type arch="x86_64" machine="pc-q35-4.2">hvm</type>
    <boot dev="hd"/>
  </os>
  <cpu mode="custom" match="exact" check="none">
    <model fallback="forbid">qemu64</model>
    <topology sockets="2" dies="1" cores="4" threads="1"/>
  </cpu>
  <devices>
    <emulator>/usr/local/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="/data/fortrace-pool/windows10-template.qcow2"/>
      <target dev="sda" bus="sata"/>
      <address type="drive" controller="0" bus="0" target="0" unit="0"/>
    </disk>
    .......
  <qemu:commandline>
    <qemu:arg value="-chardev"/>
    <qemu:arg value="socket,path=/tmp/introspector,id=chardev0,reconnect=10"/>
    <qemu:arg value="-object"/>
    <qemu:arg value="secret,id=key0,data=some"/>
    <qemu:arg value="-object"/>
    <qemu:arg value="introspection,id=kvmi,chardev=chardev0,key=key0"/>
  </qemu:commandline>
</domain>
```

libvmi was build again with debugging on, as you can see in the output.

Does anyone have any tips on how I can solve the problem? 
I would be grateful for any help and let me know if you need any more information!

Thanks! 
Tommy

**Comment by Wenzel** [comment]
Hi Tommy,

kvm-vmi relies on a Unix socket to communicate with QEMU.
You need to specify its path and connect to it (`/tmp/introspector`)

The `process-list.py` python example doesn't take additional arguments, so you can't specify the kvmi socket there.
Use the `vmi-process-list` C example from LibVMI directory:
https://github.com/libvmi/libvmi/blob/master/examples/process-list.c

It accepts a socket parameter:
![image](https://github.com/KVM-VMI/kvm-vmi/assets/964610/4af4c07c-c0b1-40cd-b96c-76991f58820a)

**Comment by dommi22m** [comment]
Hi!
Great, thank you!

I could not compile the examples from the libvmi until this morning, there the CMakeList.txt still had to be adapted because the GLib headers were not found. That's why I couldn't test them...then I might have noticed it.

I have partially adapted the python bindings so that they can now also be called with the socket.

Thanks for your quick help!
