### ISSUE TITLE
cannot stat './modules.builtin.modinfo'

### ISSUE THREAD

**Issue by chris-vdb** [KVM-VMI/kvm-vmi#174]
Hi,
I am having troubles installing the kvm kernel. While installing the modules I receive the error message 
`cp: cannot stat './modules.builtin.modinfo': No such file or directory
make: *** [Makefile:1314: _modinst_] Error 1
`
Do you have an idea, why this file could be missing?
Making the modules seemed to ended successfully:
![image](https://github.com/KVM-VMI/kvm-vmi/assets/39762590/e9badba3-3c05-4b2b-9fab-7a69a98fc9bc)

I am doing a bare-metal setup on Ubuntu 22.04.4 LTS

**Comment by Wenzel** [comment]
Hi @chris-vdb !

The kernel build is tested on ubuntu 18.04 and 22.04 in this workflow:
https://github.com/KVM-VMI/kvm-vmi/blob/master/.github/workflows/build.yml

However we don't try to install the modules with `sudo make modules_install`.

Can i ask you to try the `bindeb-pkg` method ?

**Comment by chris-vdb** [comment]
Hi @Wenzel 
Thanks for the quick response. After altering my configuration according to the configuration in the workflow, I was able to create the debian packages, thanks!
