### ISSUE TITLE
Error : Failed to fetch Ansible package during vagrant up

### ISSUE THREAD

**Issue by julie-nga** [KVM-VMI/kvm-vmi#187]
Hello,

I followed the setup guide for kvm-vmi (Option 1 -Vagrant, for Windows). I encountered this error when doing `vagrant up --provider hyperv --color` :

`    kvmi: E: Failed to fetch http://deb.debian.org/debian/pool/main/a/ansible/ansible_2.10.7%2bmerged%2bbase%2b2.10.8%2bdfsg-1_all.deb  404  Not Found [IP: 146.75.122.132 80] `

I solved it by doing `sudo apt-get update` in the VM. ( and then reprovisionning the VM with `vagrant reload --provision` ).

**Comment by Wenzel** [comment]
Hi @julie-nga

thanks for reporting this issue !
Could you check if the PR I submitted is fixing the problem ?

**Comment by julie-nga** [comment]
> Hi @julie-nga
> 
> thanks for reporting this issue ! Could you check if the PR I submitted is fixing the problem ?

Just checked, it is indeed fixing the problem !

**Comment by Wenzel** [comment]
Awesome, thanks for confirming !
