### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by qth1991** [KVM-VMI/kvm-vmi#22]
Could you tell me the detail how to use this, I don ‘t know  how to use file like kvm.yml,  my development environment is ubuntu14.04 or 16.04.I am a new recruit in this work,thank you!

**Comment by qth1991** [comment]
when i entry this "root@ubuntu:~/kvm-vmi-master/vagrant# vagrant up --provider=libvirt".there have error " vm:* The box 'debian/jessie64' could not be found."

**Comment by Wenzel** [comment]
HI @qth1991

> Could you tell me the detail how to use this, I don ‘t know how to use file like kvm.yml

you will have to be more specific, or i can't help you.

> when i entry this "root@ubuntu:~/kvm-vmi-master/vagrant# vagrant up --provider=libvirt".there have error " vm:* The box 'debian/jessie64' could not be found."

The box is here: https://app.vagrantup.com/debian/boxes/jessie64
I don't see any reason why it could not be found, except a network issue.

Please try again and post a screenshot of your error.

**Comment by qth1991** [comment]
when i entry this "root@ubuntu:~/kvm-vmi-master/vagrant# vagrant up --provider=libvirt 
![default](https://user-images.githubusercontent.com/39185602/44070285-80a99da8-9fb5-11e8-8b64-1e472c3e012f.png)

**Comment by Wenzel** [comment]
There is message saying that the box has been added to libvirt, in green

and another one in red stating that qemu has issues to get KVM capabilities.

**Comment by Wenzel** [comment]
Why are you building a Vagrant box inside Vagrant ?

**Comment by qth1991** [comment]
Good morning，I'm sorry to trouble you again. I download your code and read README they tell me " Go to the `vagrant/` sub-directory to install a development environement for `kvm-vmi` " ,So I entry vagrant/ and read README there write " Run `vagrant up --provider=libvirt`" . So I use VMware install 
 OS =censtos7.3X64  to environmental deployment .First instll  vagrant` =2.2.1,vagrant-libvirt` plugin,  ansible >= 2.2.1.0` and virtualbox5.1. then in vagrand/  enter vagrant up --provider=libvirt , appear this error. could you tell me the installation steps as I described?

**Comment by Wenzel** [comment]
I thought you were inside another Vagrant box already, the prompt you have looks the same as in Vagrant.

So, yes you are in the right way.
I don't know if VMWare is compatible with Vagrant and libvirt ?
I always used KVM to build my VMs and run Vagrant.

**Comment by Wenzel** [comment]
You cannot use VirtualBox because it doesn't support nested virtualization.

**Comment by qth1991** [comment]
Oh,  Becasue my computer OS  is  windows10, So I want to use VMware to simulate a CentOS server to deploy this environment. Is that you mean I need in CentOS install kvm  then do those deployments. or  install CentOS  replace windows10. by the way if I don't install VirtualBox the Vagrant will not work.

**Comment by Wenzel** [comment]
So, If I understand correctly

Windows 10 [VMWare]> CentOS [KVM]> Vagrant Box [KVM]> Windows guest (to be inspected)

You are looking at nested-nested virtualization, it will be wayyyyy too slow.
You need a Linux host with KVM.
