### ISSUE TITLE
 could you tell me how to install it with source compile and install  rather than use vagrant

### ISSUE THREAD

**Issue by qth1991** [KVM-VMI/kvm-vmi#23]
Because of network reasons, I always stuck in the steps of  “clone submodules”. So I want to install the source code. Because the KVM kernel used by kvm-vmi is modified, it needs to be recompiled and reinstalled. So,what is the host operating system you are using? What is the version of QEMU and linux-kernel? I will download the kvm-vmi/kvm and put it into the host computer for compilation and installation. Is that ok?

![i7 fo5e35ki bvh t _0hr](https://user-images.githubusercontent.com/39185602/44256178-feb6dd00-a23a-11e8-90b0-e0c4d7ce559a.png)
When it is stuck here, I input “ctrl+c”, then "vagrant destroy" and  "vagrant up --provider=libvirt", it will be also stuck here.It make me crazy, so I want to deploy my own environment instead of using vagrant.

**Comment by Wenzel** [comment]
Cloning the submodules takes a while, simply because it clones the KVM repository, which is huge.

You can always try by yourself:
~~~
vagrant ssh
$ cd /data/kvm-vmi
$ git submodule update --init
~~~
And you will have the progress output.

**Comment by qth1991** [comment]
yes, I ues vagrant ssh to enter vagrant@jessie:/data/kvm-vmi, download all submoudle,then how to compile it?,because in my  hostOS when I reinput "vagrant up --provider=libvirt" it just start-up   "vagrant_default"  domain Instead of  execute yaml  script.
![h 9 gxwxp q 5k 4wo3](https://user-images.githubusercontent.com/39185602/44264870-c7eec000-a256-11e8-870b-c517c678cf13.png)

**Comment by Wenzel** [comment]
you need to run the playbook from scratch
use vagrant destroy and vagrant up again

**Comment by qth1991** [comment]
but if I use vagrant destroy in host os the  /var/lib/libvirt/images/vagrant_default.img  will also destroy, then vagrant up again it will be also stuck here
![22222](https://user-images.githubusercontent.com/39185602/44265047-9a564680-a257-11e8-9642-4564ca3e5a9b.png)

**Comment by qth1991** [comment]
vagrant destroy will delete  /var/lib/libvirt/images/vagrant_default.img

**Comment by Wenzel** [comment]
Please check if clone submodules is actually stuck, and investigate to find the reason.
Otherwise, install everything on the host manually.

**Comment by qth1991** [comment]
yes it is stuck ,so I want to  install everything on the host manually but don't kown how to do this ,could you give me some advice? A little bit can help me a lot,I've been working for several days, but I haven't made any progress.
![33](https://user-images.githubusercontent.com/39185602/44265389-e48bf780-a258-11e8-80d5-38e4fa783efa.png)

**Comment by Wenzel** [comment]
Simply follow what the Ansible playbook is doing, it would be a good start.

**Comment by qth1991** [comment]
so,in provision_full/playbook.yml ?

**Comment by Wenzel** [comment]
yes

**Comment by qth1991** [comment]
ok, i try it! thank you

**Comment by qth1991** [comment]
Hi,it's me. Sorry to bother you again. When I followed the nitro.yml script execu "python3 nitro/build_libvmi.py".

![1](https://user-images.githubusercontent.com/39185602/44309763-45086980-a3fe-11e8-8f51-60479c0241ac.png)

I execute the script in order of playbook.yml ,kvm.yml, qemu.yml  nitro.yml test_vm.yml.  Is that execute kvm.yml  then reboot  entering the “Linux debian 4.9.0-nitro+ #1 SMP Sat Aug 18 21:03:09 EDT 2018 x86_64 GNU/Linux”kernel, execute the script later？

**Comment by Wenzel** [comment]
hi,
you shouldn't have to build the libvmi python bindings from Nitro, i removed them a couple of months ago, and put them in another project.

you are still sees this code because the submodules were not up to date, and pointing to older commits.
Please checkout the master branch on Nitro before running the playbook

**Comment by qth1991** [comment]
but in this project  "Nitro"  still  this code , where can find  the  new commits? thank you

**Comment by qth1991** [comment]
![tim 20180820095813](https://user-images.githubusercontent.com/39185602/44316721-c6441880-a45f-11e8-9eb6-736577cc9330.png)
Is this due to network reasons? I can download Win7x64 Enterprise.iso myself, but I don't know where to put it?

**Comment by qth1991** [comment]
I installed  win7x64.img myself, but there is an error when I was using nitro/main.py. oh, I didn't configure the network for VM  win7x64. Is this affected?
This is the VM configure file.
![3](https://user-images.githubusercontent.com/39185602/44324707-11265600-a489-11e8-8802-8de515e28ed3.png)
This is error fig
![2](https://user-images.githubusercontent.com/39185602/44324744-2dc28e00-a489-11e8-82a9-0aafa75e2a6a.png)

**Comment by Wenzel** [comment]
Did you rebooted the VM ? you have to boot on the nitro kernel that you installed earlier.

**Comment by qth1991** [comment]
No I just reboot the VMM, because the win7_64.img is copy from other computer and boot using direct command “virsh create win7_64.xml ”.Do you mean you need to use the ISO file to reinstall it? and I can't find how to do  "boot on the nitro kernel" in script yml or README.

**Comment by Wenzel** [comment]
I mean the Vagrant VM:

From the README
_Once vagrant is done provisioning the vm, run vagrant reload to reboot the box (to use the modified kernel)_

You can verify that with `uname -a` and check the kernel name

**Comment by qth1991** [comment]
I didn't use vagrant tools. I deployed my own environment based on the yaml script, and the KVM kernel I'm currently using has been nitro modified. you can see this picture 
![1](https://user-images.githubusercontent.com/39185602/44328152-66676500-a493-11e8-8279-3c9dfe643dbb.png)

I was stuck in test_vm.yml “ ./packer build --var-file=windows_7_x64.json windows.json” when I was deploying my environment.So I used my win7_64.img, but running nitro/main.py  did not succeed.

**Comment by qth1991** [comment]
oh sorry ,there is a new error

**Comment by qth1991** [comment]
![13](https://user-images.githubusercontent.com/39185602/44331421-032e0080-a49c-11e8-837f-96a0bb444605.png)


Remind me to install rekall ,but I have installed rekall.

**Comment by qth1991** [comment]
eee.... which is correctly.
first
![1](https://user-images.githubusercontent.com/39185602/44332386-7df81b00-a49e-11e8-9923-6e212a937b4c.png)
second
![2](https://user-images.githubusercontent.com/39185602/44332389-805a7500-a49e-11e8-9bcf-6ac2e0831f42.png)

**Comment by Wenzel** [comment]
You just found an issue in my README, congrats.

I have instructed to use `pip3`, however, i'm calling my script with Python2, so it has to been installed with `pip2`, or `pip`.

I will update the README and fix this issue.
Thanks for reporting.

**Comment by qth1991** [comment]
Oh，Is that all the version is python2.7 or just for rekall? and which python version to  run  nitro/main.py 
![tim 20180820215700](https://user-images.githubusercontent.com/39185602/44344924-65026080-a4c4-11e8-86a4-f5608baf9fdd.png)

**Comment by Wenzel** [comment]
Python 2.7 is only needed for Rekall.

**Comment by qth1991** [comment]
![1](https://user-images.githubusercontent.com/39185602/44376476-5c914080-a52b-11e8-963e-c39eb4441f2c.png)
![2](https://user-images.githubusercontent.com/39185602/44376482-6024c780-a52b-11e8-9d79-d3c92c2cf608.png)

**Comment by qth1991** [comment]
eeeem... I don't how to fix this "ERROR:root:No profiles match this image. Try specifying manually."

**Comment by qth1991** [comment]
why direct execute "python3 main.py win7x64" It's make "ERROR:root:No profiles match this image. Try specifying manually." 
![1](https://user-images.githubusercontent.com/39185602/44377147-27d2b880-a52e-11e8-92eb-3e0eff679ce7.png)
![3](https://user-images.githubusercontent.com/39185602/44377155-2f925d00-a52e-11e8-95a8-56795ae01591.png)

**Comment by qth1991** [comment]
but I first execute “python3 main.py --nobackend win7x64”, then push "ctrl+c" and  execute “python3 main.py win7x64” immediately， It's can run in right way.
![4](https://user-images.githubusercontent.com/39185602/44377412-3372af00-a52f-11e8-83cd-d87783fb26ee.png)

**Comment by Wenzel** [comment]
The previous error refers to Rekall not being able to identify the operating system.
You should investigate that with Rekall guys.

Nice !
it seems that it works now !
