### ISSUE TITLE
libvmi error

### ISSUE THREAD

**Issue by bigbigbanana** [KVM-VMI/kvm-vmi#29]
When i run libvmi examples,it shows some errors like the picture below says,how can i solve it?
![2018-09-20 15-57-31](https://user-images.githubusercontent.com/24928429/45804329-635bd080-bcee-11e8-83f8-d976f95d4cf3.png)

**Comment by Wenzel** [comment]
Hi,

as I told you before, this repo is not dedicated to LibVMI, so i cannot provide any support for this project.
you need to open an issue on LibVMI.
