### ISSUE TITLE
 No such file error with "nitro/build_libvmi.py"

### ISSUE THREAD

**Issue by Bondey** [KVM-VMI/kvm-vmi#32]
I've been trying to "vagrant up" and i keep getting this error:

~~~
fatal: [default]: FAILED! => {
	"changed": true, 
	"cmd": ["python3",  "nitro/build_libvmi.py"], 
	"delta": "0:00:00.047952", 
	"end": "2019-02-25 19:24:52.096462", 
	"msg": "non-zero return code", 
	"rc": 2, 
	"start": "2019-02-25 19:24:52.048510", 
	"stderr": "python3: can't open file 'nitro/build_libvmi.py': [Errno 2] No such file or directory", 
	"stderr_lines": ["python3: can't open file 'nitro/build_libvmi.py': [Errno 2] No such file or directory"], 
	"stdout": "", 
	"stdout_lines": []
}
~~~

i've made a `git clone --recursive https://github.com/KVM-VMI/kvm-vmi.git`
And all dependences are updated afaik...
My SO is "Ubuntu 18.04" 

I have already made a "vagrant destroy" and up again.
¿Any idea?

thanks!

**Comment by Wenzel** [comment]
Hi,

good catch, there is a bug in the playbook !
I have no way to deploy the vagrant automatically via Travis, that's why it might be broken despite my efforts.

Also, i have been busy with other projects, and i couldn't maintain this repo as much as I wanted.
But the fix is the following:
I suppose you are on `master`

replace this task:
https://github.com/KVM-VMI/kvm-vmi/blob/master/vagrant/provision_full/nitro.yml#L40

by
~~~YAML
- name: install libvmi python bindings
  command: pip install libvmi
~~~

**Comment by Bondey** [comment]
After changing this lines, I'm getting this error from pip:
[err.txt](https://github.com/KVM-VMI/kvm-vmi/files/2906609/err.txt)

I checked that all dependences listed on libvmi project are intealled:
"apt-get install autotools-dev automake flex bison libglib2.0-dev libvirt-dev libjson-c-dev libyajl-dev"

:/

**Comment by Wenzel** [comment]
try installing the latest libvmi from github.
you need to install CMake also.

**Comment by Bondey** [comment]
allright i've got a bit of time this weekend and messed up with this a few more.

the compile of libvmi was showing me this error:
`Unknown CMake command "target_sources"`

Wich comes because of the old version of cmake that debian has in repos, and the usage of "target_sources" at the CMakeLists.txt 

installed cmake from source, and everything worked fine :)

**Comment by Wenzel** [comment]
@Bondey interesting, there is a small bug in our Cmake then.
Can you make a PR to increase the minimum version to `3.1` ?

thank you.

**Comment by Wenzel** [comment]
Closing this issue as the bug has been resolved.
