### ISSUE TITLE
libvmi example process-list error

### ISSUE THREAD

**Issue by Pai-Po** [KVM-VMI/kvm-vmi#44]
a example of libvmi, proces-list, doesn't work.
due to before create /tmp/introspection socket, libvmi will to get the existing vm'info first, but qemu need to connect /tmp/introspection to launch. it seems like a deadlock, i think. may be i am wrong.

**Comment by mtarral** [comment]
Hi,

Double check that you are running with the modified QEMU.

Canyou enable the debug output and paste it here ?

**Comment by Pai-Po** [comment]
![image](https://user-images.githubusercontent.com/12437819/70804291-141d2680-1df1-11ea-8506-3d122b77341c.png)
![image](https://user-images.githubusercontent.com/12437819/70804340-3020c800-1df1-11ea-8e95-d023d6a10f74.png)
![image](https://user-images.githubusercontent.com/12437819/70804367-43cc2e80-1df1-11ea-9b79-7f421e282ef2.png)

maybe i don't know how to lanuch the vm in right order.
can you give a tutorial about how to use the libvmi's example with the kvm-vmi?

**Comment by mtarral** [comment]
> can you give a tutorial about how to use the libvmi's example with the kvm-vmi?

Did you follow the setup tutorial  ?
https://github.com/KVM-VMI/kvm-vmi/wiki/KVM-VMI-setup

Don't forget this part in the domain XML:
~~~XML
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
    <qemu:commandline>
      <qemu:arg value='-chardev'/>
      <qemu:arg value='socket,path=/tmp/introspector,id=chardev0,reconnect=10'/>
      <qemu:arg value='-object'/>
      <qemu:arg value='secret,id=key0,data=some'/>
      <qemu:arg value='-object'/>
      <qemu:arg value='introspection,id=kvmi,chardev=chardev0,key=key0'/>
      <qemu:arg value='-accel'/>
      <qemu:arg value='kvm,introspection=kvmi'/>
  </qemu:commandline>
~~~

You should try first with libkvmi's test program `kvmi-test`.

**Comment by Pai-Po** [comment]
> > can you give a tutorial about how to use the libvmi's example with the kvm-vmi?
> 
> Did you follow the setup tutorial ?
> https://github.com/KVM-VMI/kvm-vmi/wiki/KVM-VMI-setup
> 
> Don't forget this part in the domain XML:
> 
> ```
> <domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
>     <qemu:commandline>
>       <qemu:arg value='-chardev'/>
>       <qemu:arg value='socket,path=/tmp/introspector,id=chardev0,reconnect=10'/>
>       <qemu:arg value='-object'/>
>       <qemu:arg value='secret,id=key0,data=some'/>
>       <qemu:arg value='-object'/>
>       <qemu:arg value='introspection,id=kvmi,chardev=chardev0,key=key0'/>
>       <qemu:arg value='-accel'/>
>       <qemu:arg value='kvm,introspection=kvmi'/>
>   </qemu:commandline>
> ```
> 
> You need to set the same socket path: <qemu:arg value='socket,**path=/tmp/introspector**,id=chardev0,reconnect=10'/>
> 
> You should try first with libkvmi's test program `kvmi-test`.

i configure the environment step by step according to the KVM-VMI-setup tutorial, and kvmi-test run successfully. now i want extend some functions, so i test the kvm-process-list, but it failed. 
can you run it successfully?i think it is a logic error of patched libvmi

**Comment by Wenzel** [comment]
> i configure the environment step by step according to the KVM-VMI-setup tutorial, and kvmi-test run successfully. 

Good :+1: 

>  so i test the kvm-process-list

`vmi-process-list`

> can you run it successfully?i think it is a logic error of patched libvmi

Can you give me some debug output ?
Enable everything with `cmake -DVMI_DEBUG=__VMI_DEBUG_ALL -DENV_DEBUG=ON ..`

And then `LIBVMI_DEBUG=1 ./examples/vmi-process-list ...`

**Comment by Pai-Po** [comment]
hi guy, i fixed this problem. 
![image](https://user-images.githubusercontent.com/12437819/77052215-76488180-6a07-11ea-9419-55a9d0ab8498.png)
you should make the wait time longer, not equal to the reconnect time.
