### ISSUE TITLE
Cannot install any new VMs

### ISSUE THREAD

**Issue by allewwaly** [KVM-VMI/kvm-vmi#57]
After compiling the kvm version of kvm-vmi, I cannot install any new VMs as it always counter the following error either using virt-manager or virt-install:
`
ERROR    internal error: process exited while connecting to monitor: 2020-07-10T08:25:29.702114Z qemu-system-x86_64: -enable-kvm: unsupported machine type
Use -machine help to list supported machines
`
I've checked the machine type and it was in the list of supported machine type.

**Comment by Wenzel** [comment]
Hi

I think that the KVM machine type is not available for some reason.
Check what's available on both qemu:///session and qemu:///system with `virsh capabilities`

**Comment by allewwaly** [comment]
`john@ubuntu1804:~$ virsh capabilities 
<capabilities>

  <host>
    <uuid>c81e4d56-8ff1-3b7d-4020-f94a558e8b2d</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>Broadwell-noTSX-IBRS</model>
      <vendor>Intel</vendor>
      <microcode version='43'/>
      <topology sockets='1' cores='1' threads='1'/>
      <feature name='vme'/>
      <feature name='ss'/>
      <feature name='vmx'/>
      <feature name='osxsave'/>
      <feature name='f16c'/>
      <feature name='rdrand'/>
      <feature name='hypervisor'/>
      <feature name='arat'/>
      <feature name='tsc_adjust'/>
      <feature name='ssbd'/>
      <feature name='xsaveopt'/>
      <feature name='pdpe1gb'/>
      <feature name='abm'/>
      <feature name='invtsc'/>
      <pages unit='KiB' size='4'/>
      <pages unit='KiB' size='2048'/>
      <pages unit='KiB' size='1048576'/>
    </cpu>
    <power_management>
      <suspend_mem/>
      <suspend_disk/>
      <suspend_hybrid/>
    </power_management>
    <migration_features>
      <live/>
      <uri_transports>
        <uri_transport>tcp</uri_transport>
        <uri_transport>rdma</uri_transport>
      </uri_transports>
    </migration_features>
    <topology>
      <cells num='1'>
        <cell id='0'>
          <memory unit='KiB'>4012748</memory>
          <pages unit='KiB' size='4'>1003187</pages>
          <pages unit='KiB' size='2048'>0</pages>
          <pages unit='KiB' size='1048576'>0</pages>
          <distances>
            <sibling id='0' value='10'/>
          </distances>
          <cpus num='1'>
            <cpu id='0' socket_id='0' core_id='0' siblings='0'/>
          </cpus>
        </cell>
      </cells>
    </topology>
    <cache>
      <bank id='0' level='3' type='both' size='4' unit='MiB' cpus='0'/>
    </cache>
    <secmodel>
      <model>none</model>
      <doi>0</doi>
    </secmodel>
    <secmodel>
      <model>dac</model>
      <doi>0</doi>
      <baselabel type='kvm'>+64055:+113</baselabel>
      <baselabel type='qemu'>+64055:+113</baselabel>
    </secmodel>
  </host>

  <guest>
    <os_type>hvm</os_type>
    <arch name='i686'>
      <wordsize>32</wordsize>
      <emulator>/usr/bin/qemu-system-i386</emulator>
      <machine maxCpus='255'>pc-i440fx-bionic</machine>
      <machine canonical='pc-i440fx-bionic' maxCpus='255'>ubuntu</machine>
      <machine maxCpus='1'>isapc</machine>
      <machine maxCpus='255'>pc-1.1</machine>
      <machine maxCpus='255'>pc-1.2</machine>
      <machine maxCpus='255'>pc-1.3</machine>
      <machine maxCpus='255'>pc-i440fx-zesty</machine>
      <machine maxCpus='255'>pc-i440fx-2.8</machine>
      <machine maxCpus='255'>pc-1.0</machine>
      <machine maxCpus='255'>pc-i440fx-2.9</machine>
      <machine maxCpus='255'>pc-i440fx-2.6</machine>
      <machine maxCpus='255'>pc-i440fx-2.7</machine>
      <machine maxCpus='128'>xenfv</machine>
      <machine maxCpus='255'>pc-i440fx-wily</machine>
      <machine maxCpus='255'>pc-i440fx-2.3</machine>
      <machine maxCpus='255'>pc-i440fx-2.4</machine>
      <machine maxCpus='255'>pc-i440fx-2.5</machine>
      <machine maxCpus='255'>pc-i440fx-yakkety</machine>
      <machine maxCpus='255'>pc-i440fx-2.1</machine>
      <machine maxCpus='255'>pc-i440fx-2.2</machine>
      <machine maxCpus='255'>pc-i440fx-2.0</machine>
      <machine maxCpus='255'>pc-q35-yakkety</machine>
      <machine maxCpus='255'>pc-i440fx-bionic-hpb</machine>
      <machine maxCpus='288'>pc-q35-2.11</machine>
      <machine canonical='pc-q35-2.11' maxCpus='288'>q35</machine>
      <machine maxCpus='255'>pc-i440fx-xenial</machine>
      <machine maxCpus='1'>xenpv</machine>
      <machine maxCpus='288'>pc-q35-2.10</machine>
      <machine maxCpus='288'>pc-q35-bionic-hpb</machine>
      <machine maxCpus='255'>pc-q35-xenial</machine>
      <machine maxCpus='255'>pc-i440fx-artful</machine>
      <machine maxCpus='255'>pc-i440fx-1.7</machine>
      <machine maxCpus='255'>pc-i440fx-2.1</machine>
      <machine maxCpus='255'>pc-i440fx-2.2</machine>
      <machine maxCpus='255'>pc-i440fx-2.0</machine>
      <machine maxCpus='255'>pc-q35-yakkety</machine>
      <machine maxCpus='255'>pc-i440fx-bionic-hpb</machine>
      <machine maxCpus='288'>pc-q35-2.11</machine>
      <machine canonical='pc-q35-2.11' maxCpus='288'>q35</machine>
      <machine maxCpus='255'>pc-i440fx-xenial</machine>
      <machine maxCpus='1'>xenpv</machine>
      <machine maxCpus='288'>pc-q35-2.10</machine>
      <machine maxCpus='288'>pc-q35-bionic-hpb</machine>
      <machine maxCpus='255'>pc-q35-xenial</machine>
      <machine maxCpus='255'>pc-i440fx-artful</machine>
      <machine maxCpus='255'>pc-i440fx-1.7</machine>
      <machine maxCpus='288'>pc-q35-2.9</machine>
      <machine maxCpus='255'>pc-0.15</machine>
      <machine maxCpus='255'>pc-i440fx-1.5</machine>
      <machine maxCpus='255'>pc-q35-2.7</machine>
      <machine maxCpus='255'>pc-i440fx-1.6</machine>
      <machine maxCpus='255'>pc-i440fx-2.11</machine>
      <machine canonical='pc-i440fx-2.11' maxCpus='255'>pc</machine>
      <machine maxCpus='288'>pc-q35-2.8</machine>
      <machine maxCpus='288'>pc-q35-zesty</machine>
      <machine maxCpus='255'>pc-0.13</machine>
      <machine maxCpus='288'>pc-q35-artful</machine>
      <machine maxCpus='255'>pc-0.14</machine>
      <machine maxCpus='255'>pc-q35-2.4</machine>
      <machine maxCpus='255'>pc-i440fx-trusty</machine>
      <machine maxCpus='255'>pc-q35-2.5</machine>
      <machine maxCpus='255'>pc-q35-2.6</machine>
      <machine maxCpus='255'>pc-i440fx-1.4</machine>
      <machine maxCpus='255'>pc-i440fx-2.10</machine>
      <machine maxCpus='255'>pc-0.11</machine>
      <machine maxCpus='255'>pc-0.12</machine>
      <machine maxCpus='288'>pc-q35-bionic</machine>
      <machine maxCpus='255'>pc-0.10</machine>
      <domain type='qemu'/>
      <domain type='kvm'>
        <emulator>/usr/bin/kvm-spice</emulator>
        <machine maxCpus='255'>pc-i440fx-bionic</machine>
        <machine canonical='pc-i440fx-bionic' maxCpus='255'>ubuntu</machine>
        <machine maxCpus='1'>isapc</machine>
        <machine maxCpus='255'>pc-1.1</machine>
        <machine maxCpus='255'>pc-1.2</machine>
        <machine maxCpus='255'>pc-1.3</machine>
        <machine maxCpus='255'>pc-i440fx-zesty</machine>
        <machine maxCpus='255'>pc-i440fx-2.8</machine>
        <machine maxCpus='255'>pc-1.0</machine>
        <machine maxCpus='255'>pc-i440fx-2.9</machine>
        <machine maxCpus='255'>pc-i440fx-2.6</machine>
        <machine maxCpus='255'>pc-i440fx-2.7</machine>
        <machine maxCpus='128'>xenfv</machine>
        <machine maxCpus='255'>pc-i440fx-wily</machine>
        <machine maxCpus='255'>pc-i440fx-2.3</machine>
        <machine maxCpus='255'>pc-i440fx-2.4</machine>
        <machine maxCpus='255'>pc-i440fx-2.5</machine>
        <machine maxCpus='255'>pc-i440fx-yakkety</machine>
        <machine maxCpus='255'>pc-i440fx-2.1</machine>
        <machine maxCpus='255'>pc-i440fx-2.2</machine>
        <machine maxCpus='255'>pc-i440fx-2.0</machine>
        <machine maxCpus='255'>pc-q35-yakkety</machine>
        <machine maxCpus='255'>pc-i440fx-bionic-hpb</machine>
        <machine maxCpus='288'>pc-q35-2.11</machine>
        <machine canonical='pc-q35-2.11' maxCpus='288'>q35</machine>
        <machine maxCpus='255'>pc-i440fx-xenial</machine>
        <machine maxCpus='1'>xenpv</machine>
        <machine maxCpus='288'>pc-q35-2.10</machine>
        <machine maxCpus='288'>pc-q35-bionic-hpb</machine>
        <machine maxCpus='255'>pc-q35-xenial</machine>
        <machine maxCpus='255'>pc-i440fx-artful</machine>
      <machine maxCpus='255'>pc-i440fx-1.7</machine>
      <machine maxCpus='288'>pc-q35-2.9</machine>
      <machine maxCpus='255'>pc-0.15</machine>
      <machine maxCpus='255'>pc-i440fx-1.5</machine>
      <machine maxCpus='255'>pc-q35-2.7</machine>
      <machine maxCpus='255'>pc-i440fx-1.6</machine>
      <machine maxCpus='255'>pc-i440fx-2.11</machine>
      <machine maxCpus='288'>pc-q35-2.8</machine>
      <machine maxCpus='255'>pc-0.13</machine>
      <machine maxCpus='255'>pc-0.14</machine>
      <machine maxCpus='255'>pc-q35-2.4</machine>
      <machine maxCpus='255'>pc-q35-2.5</machine>
      <machine maxCpus='255'>pc-q35-2.6</machine>
      <machine maxCpus='255'>pc-i440fx-1.4</machine>
      <machine maxCpus='255'>pc-i440fx-2.10</machine>
      <machine maxCpus='255'>pc-0.11</machine>
      <machine maxCpus='255'>pc-0.12</machine>
      <machine maxCpus='255'>pc-0.10</machine>
      <domain type='qemu'/>
      <domain type='kvm'>
        <emulator>/usr/bin/kvm-spice</emulator>
        <machine maxCpus='255'>pc-i440fx-bionic</machine>
        <machine canonical='pc-i440fx-bionic' maxCpus='255'>ubuntu</machine>
        <machine maxCpus='1'>isapc</machine>
        <machine maxCpus='255'>pc-1.1</machine>
        <machine maxCpus='255'>pc-1.2</machine>
        <machine maxCpus='255'>pc-1.3</machine>
        <machine maxCpus='255'>pc-i440fx-zesty</machine>
        <machine maxCpus='255'>pc-i440fx-2.8</machine>
        <machine maxCpus='255'>pc-1.0</machine>
        <machine maxCpus='255'>pc-i440fx-2.9</machine>
        <machine maxCpus='255'>pc-i440fx-2.6</machine>
        <machine maxCpus='255'>pc-i440fx-2.7</machine>
        <machine maxCpus='128'>xenfv</machine>
        <machine maxCpus='255'>pc-i440fx-wily</machine>
        <machine maxCpus='255'>pc-i440fx-2.3</machine>
        <machine maxCpus='255'>pc-i440fx-2.4</machine>
        <machine maxCpus='255'>pc-i440fx-2.5</machine>
        <machine maxCpus='255'>pc-i440fx-yakkety</machine>
        <machine maxCpus='255'>pc-i440fx-2.1</machine>
        <machine maxCpus='255'>pc-i440fx-2.2</machine>
        <machine maxCpus='255'>pc-i440fx-2.0</machine>
        <machine maxCpus='255'>pc-q35-yakkety</machine>
        <machine maxCpus='255'>pc-i440fx-bionic-hpb</machine>
        <machine maxCpus='288'>pc-q35-2.11</machine>
        <machine canonical='pc-q35-2.11' maxCpus='288'>q35</machine>
        <machine maxCpus='255'>pc-i440fx-xenial</machine>
        <machine maxCpus='1'>xenpv</machine>
        <machine maxCpus='288'>pc-q35-2.10</machine>
        <machine maxCpus='288'>pc-q35-bionic-hpb</machine>
        <machine maxCpus='255'>pc-q35-xenial</machine>
        <machine maxCpus='255'>pc-i440fx-artful</machine>
        <machine maxCpus='255'>pc-i440fx-1.7</machine>
        <machine maxCpus='288'>pc-q35-2.9</machine>
        <machine maxCpus='255'>pc-0.15</machine>
        <machine maxCpus='255'>pc-i440fx-1.5</machine>
        <machine maxCpus='255'>pc-q35-2.7</machine>
        <machine maxCpus='255'>pc-i440fx-1.6</machine>
        <machine maxCpus='255'>pc-i440fx-2.11</machine>
        <machine canonical='pc-i440fx-2.11' maxCpus='255'>pc</machine>
        <machine maxCpus='288'>pc-q35-2.8</machine>
        <machine maxCpus='288'>pc-q35-zesty</machine>
        <machine maxCpus='255'>pc-0.13</machine>
        <machine maxCpus='288'>pc-q35-artful</machine>
        <machine maxCpus='255'>pc-0.14</machine>
        <machine maxCpus='255'>pc-q35-2.4</machine>
        <machine maxCpus='255'>pc-i440fx-trusty</machine>
        <machine maxCpus='255'>pc-q35-2.5</machine>
        <machine maxCpus='255'>pc-q35-2.6</machine>
        <machine maxCpus='255'>pc-i440fx-1.4</machine>
        <machine maxCpus='255'>pc-i440fx-2.10</machine>
        <machine maxCpus='255'>pc-0.11</machine>
        <machine maxCpus='255'>pc-0.12</machine>
        <machine maxCpus='288'>pc-q35-bionic</machine>
        <machine maxCpus='255'>pc-0.10</machine>
      </domain>
    </arch>
    <features>
      <cpuselection/>
      <deviceboot/>
      <disksnapshot default='on' toggle='no'/>
      <acpi default='on' toggle='yes'/>
      <apic default='on' toggle='no'/>
    </features>
  </guest>

</capabilities>
`
The command I used to create a vm is:
`virt-install --name "mywin" --ram 8192 --cpu host --os-variant win10 --vcpu 8 --disk /var/lib/libvirt/images/mywin.qcow2,bus=ide --network bridge=virbr0 --import
`
No specific devices are assigned.

**Comment by Wenzel** [comment]
Can you run ` qemu-system-i386 -enable-kvm` and see if this works ?

if it does, the error is in the machine type requested in the xml.
compare it with your virsh capabilities to better understand the issue.

**Comment by allewwaly** [comment]
`qemu-system-i386 -enable-kvm` works, however if I specify any machine type, an error appears as following:
```
 virt-install --name "win7" --machine=pc-1.3 --ram 1024 --cpu host --os-variant win7 --vcpu 1 --disk /mnt/hgfs/vm/win7.qcow2 --network bridge=virbr0 --import
Starting install...
**ERROR    internal error: process exited while connecting to monitor: 2020-07-21T09:57:19.885645Z qemu-system-x86_64: can't apply global Broadwell-noTSX-IBRS-x86_64-cpu.ssbd=on: Property '.ssbd' not found**
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start win7
otherwise, please restart your installation.
```
Some types of machine such as pc-q35-2.12 and =pc-i440fx-2.12 meets another error:
```
 virt-install --name "win7" --machine=pc-q35-2.12 --ram 1024 --cpu host --os-variant win7 --vcpu 1 --disk /mnt/hgfs/vm/win7.qcow2 --network bridge=virbr0 --import
WARNING  KVM acceleration not available, using 'qemu'

Starting install...
**ERROR    unsupported configuration: USB redirection is not supported by this version of QEMU**
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start win7
otherwise, please restart your installation.
```
So what machine type should I choose to be able to meet the requirements of KVM-VMI. VMs installed before the KVM-VMI can work after modify the XML configurations as `https://github.com/KVM-VMI/kvm-vmi/wiki/KVM-VMI-setup#preparing-a-domain`. But cannot install any new VMs as the above errors.

**Comment by Wenzel** [comment]
You can get a list of the supported machine types with
`qemu-system-x86_64 -machine help`

you should use kvm-vmi's QEMU to get this list.
then modify the XML and set the machine type accordingly
