### ISSUE TITLE
USB REDIRECTION NOT SUPPPORT

### ISSUE THREAD

**Issue by helpingKVM-VMI** [KVM-VMI/kvm-vmi#58]
I have a question about the environment for building KVM-VMI.
I use Ubuntu 18.04 for both host OS and guest OS.
I was doing setup work for KVM-VMI at the link below. Finish XML editing and set up libkvmi

Then I started Ubuntu 18.04 (guest OS) in virt-manager. However, QEMU's USB redirection does not support it, so it cannot be started. I would appreciate if anyone could tell me the solution.

<ERROR>
 unsupported configuration: USB redirection is not supported by this version of QEMU

Traceback (most recent call last):
File "/usr/share/virt-manager/virtManager/asyncjob.py", line 89, in cb_wrapper
callback(asyncjob, *args, **kwargs)
File "/usr/share/virt-manager/virtManager/asyncjob.py", line 125, in tmpcb
callback(*args, **kwargs)
File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 82, in newfn
ret = fn(self, *args, **kwargs)
File "/usr/share/virt-manager/virtManager/domain.py", line 1508, in startup
self._backend.create()
File "/usr/lib/python2.7/dist-packages/libvirt.py", line 1062, in create
if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: unsupported configuration: USB redirection is not supported by this version of QEMU

**Comment by Wenzel** [comment]
Hi @helpingKVM-VMI,

This problem is due to virt-manager inserting 2 USB redirection devices by default.

QEMU needs to have USB support to emulate these devices, however, the configure command line that we propose in the setup wiki does not include USB features.

You have 2 solutions :
- remove the 2 USB redirections devices from your domain, either with virt-manager or by editing the XML manually (this is my solution)
- add USB support in your QEMU build (look at ./configure --help options) (you will likely need to install some usb libraries.)

I hope this helps !

**Comment by helpingKVM-VMI** [comment]
Hello.
The default USB redirection settings for my guest OS are:
  <redirdev bus='usb' type='spicevmc'>
       <address type='usb' bus='0' port='3'/>
     </redirdev>
     <redirdev bus='usb' type='spicevmc'>
       <address type='usb' bus='0' port='6'/>
     </redirdev>

Is it possible to solve this by deleting these as one solution?

**Comment by helpingKVM-VMI** [comment]
![キャプチャ2](https://user-images.githubusercontent.com/68001047/87292934-85b28400-c53c-11ea-81f1-42af1fde2624.PNG)

**Comment by Wenzel** [comment]
Yes, remove the USB redirection sections from your domain xml

**Comment by helpingKVM-VMI** [comment]
I've deleted all the USB redirector lists, but there's a new issue. Does this mean adding a new USB redirector?
<ERROR>
 internal error: process exited while connecting to monitor: 2020-07-13T10:15:01.678959Z qemu-system-x86_64: -machine pc-i440fx-bionic,accel=kvm,usb=off,vmport=off,dump-guest- core=off: unsupported machine type
Use -machine help to list supported machines

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 89, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 125, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 82, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1508, in startup
    self._backend.create()
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 1062, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: internal error: process exited while connecting to monitor: 2020-07-13T10:15:01.678959Z qemu-system-x86_64: -machine pc-i440fx-bionic,accel=kvm,usb=off,vmport=off,dump- guest-core=off: unsupported machine type
Use -machine help to list supported machines

**Comment by helpingKVM-VMI** [comment]
Thanks a lot to solve this issue.

**Comment by RonnyJiang** [comment]
Thank you very much for being helpful to me

**Comment by realyukii** [comment]
thank you Wenzel for explaining it ^^

solved by just installing `qemu-hw-usb-redirect` arch linux package

**Comment by realyukii** [comment]
> QEMU needs to have USB support to emulate these devices, however, the configure command line that we propose in the setup wiki does not include USB features.

by the way, what is the use of USB redirection? I'm not sure whether should remove the option or just install the required package

**Comment by KaziiTheAvali** [comment]
> > QEMU needs to have USB support to emulate these devices, however, the configure command line that we propose in the setup wiki does not include USB features.
> 
> by the way, what is the use of USB redirection? I'm not sure whether should remove the option or just install the required package

for bolth keyboard and mouses you are emulating a mouse and keyboard. you can only access customization for certain deviceses such as redragon via usb passthrough/usb redirection.
