### ISSUE TITLE
KVM－VMI　SET UP ISSUE

### ISSUE THREAD

**Issue by helpingKVM-VMI** [KVM-VMI/kvm-vmi#59]
I want to edit XML. However, writing is not possible due to the following error message. Please tell me the solution.
<ERROR LOG>
error: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin /usr/ local/bin/qemu-system-x86_64 -help) unexpected exit status 126: libvirt: error: cannot execute binary /usr/local/bin/qemu-system-x86_64: no permission

Also, after editing and saving, if you check the contents again, it will return to the state before the change. Please tell me the solution for this as well.

**Comment by Wenzel** [comment]
Hi

This is an apparmor issue, protecting your system from untrusted binaries.

You can check this ansible task to allow a specific qemu binary in the libvirt apparmor profile.

**Comment by helpingKVM-VMI** [comment]
@Wenzel 
HI
Thank you very much.
It turned out to be an apparmor issue.
However, I am a beginner and I don't know how to open or check the libvirt apparmor profile.
Sorry to trouble you, but can you write a command line for that?
Thank you.

**Comment by Wenzel** [comment]
Sorry no, this is not a kvm-vmi issue and i gave you a workaround.

**Comment by helpingKVM-VMI** [comment]
@Wenzel 
OK.
Thanks to help me!
