### ISSUE TITLE
SET UP ISSUE #2

### ISSUE THREAD

**Issue by helpingKVM-VMI** [KVM-VMI/kvm-vmi#60]
I finished the setup work by typing the following command.
$ cd kvm-vmi/kvm/tools/kvm/kvmi
$ make
$ sudo make install
![問題場面](https://user-images.githubusercontent.com/68001047/87763418-b867bf80-c84f-11ea-927a-692c94d7a8eb.PNG)

After that I started the test program and tried to see the contents of the guest OS in virt-manager, but it is hampered by the error content in the image.
Please tell me the specific solution. Thank you.

**Comment by Wenzel** [comment]
Hi,

You have a library path issue.
Check your `LD_LIBRARY_PATH`.
Apprently it doesn't include the current directory.

**Comment by Wenzel** [comment]
Also you don't need sudo.

Try this:
`LD_LIBRARY_PATH=. ./kvmi-test /tmp/introspector`

**Comment by helpingKVM-VMI** [comment]
@Wenzel 
Hello.
The command that asked me to type in
Try this:
LD_LIBRARY_PATH=. ./kvmi-test /tmp/introspector
When I did this, it came to be displayed on the terminal like the following image.
![問題場面３](https://user-images.githubusercontent.com/68001047/87776144-42208880-c862-11ea-95f9-a9759af298c5.PNG)

Do you think this is a success?
Also, if you want to see more various contents, is it a flow of installing and setting up LIBVMI at the end of the page?
Please give each answer.

**Comment by Wenzel** [comment]
Yes the kvmi-test executed successfully.

I don't understand the second question.

**Comment by helpingKVM-VMI** [comment]
@Wenzel 
Hello.
I found that kvmi-test was successful. Thank you for your support.
The second question is that libvmi is shown in the dependencies at the end of the KVM-VMI setup page.
Does this mean install and setup when you want to see more guest OS memory map contents?

**Comment by Wenzel** [comment]
The wiki mention how to install libvmi gives you more high-level features.

You can check the libvmi repo for detailed instructions.

**Comment by helpingKVM-VMI** [comment]
@Wenzel 
Thank you for your polite answer.
Check the wiki.
