### ISSUE TITLE
Propose an edit to the kvm vmi setup wiki

### ISSUE THREAD

**Issue by Tanjim131** [KVM-VMI/kvm-vmi#70]
On setup option 2 (Bare-metal setup), there is a command:

`sudo make modules_install`

I think the underscore shouldn't be there.

**Comment by Wenzel** [comment]
I don't understand, this is a legitimate makefile target, to install the modules.
https://superuser.com/a/770761

**Comment by Tanjim131** [comment]
I ran into this error: 

```
cp: cannot stat './modules.order': No such file or directory
make: *** [Makefile:1286: _modinst_] Error 1
```
I'm running this on Ubuntu 20 using gcc 8. I don't know if this is a local issue. Running without the underscore worked for me. Sorry for the bother.

**Comment by Wenzel** [comment]
It works because `modules` and `install` are 2 valid targets.
Still, you are not installing the modules, 
You compile them with the former, and you install the kernel with the latter.

**Comment by Tanjim131** [comment]
I've already ran the `sudo make modules install` command. Do I need to run `sudo make modules_install` after it finishes? Or do I have to start from scratch?

**Comment by Wenzel** [comment]
Did you run `make modules` before `make modules_install` ?

**Comment by Tanjim131** [comment]
No I didn't.

**Comment by Wenzel** [comment]
Furst you don't need to compile as root.
Second, you need to install the modules.

Just follow the wiki page.

**Comment by Tanjim131** [comment]
I have successfully run all the commands. But after reboot, ubuntu 20 is loaded. I don't get any prompt/cmd to run the commands. kvm image is installed at kvm-vmi/kvm/arch/x86/boot/bzImage. Do I need to do anything else?

**Comment by Wenzel** [comment]
> I don't get any prompt/cmd to run the command uname -a

I don't understand, you can't boot on your system anymore ?

**Comment by Tanjim131** [comment]
![1](https://user-images.githubusercontent.com/32413465/92518567-5cf7f380-f23a-11ea-9aae-816b7b114f9d.jpg)

This is what I get when I turn the computer on.

**Comment by Wenzel** [comment]
`missing modules`, I suppose you installed the kernel and not the modules.

**Comment by mtarral** [comment]
Did you managed to boot on the new kernel ?

**Comment by Tanjim131** [comment]
I ended up following the vagrant setup and installed the kernel successfully. I'm closing this issue.

**Comment by mtarral** [comment]
Great !
