### ISSUE TITLE
Failed to init LibVMI library 

### ISSUE THREAD

**Issue by pranto47** [KVM-VMI/kvm-vmi#76]
I had followed "Vagrant - Virtual Machine based setup" of https://kvm-vmi.github.io/kvm-vmi/kvmi/setup.html and successfully installed it on my system. After that I ran the ''./vmi-process-list -n vagrant_kvmi -s /tmp/introspector'' command and encountered the following error:

--Destroying KVM driver
--found KVM
--KVMi socket path: /tmp/introspector
--libvirt version 4000000
--Connecting to KVMI...
--KVMi handshake
--KVMi Error: failed to retrieve the protocol version (invalid authentication token?)
--KVMI failed
--Destroying KVM driver
Failed to init LibVMI library.

can someone explain why Iam getting this error?
Thanks.

**Comment by mtarral** [comment]
Hi,

The vagrant based setup configures KVM-VMI in a VM on your system.
If you want to introspect a guest, this needs to be done inside this VM, not on your host.

Host (your laptop) -> Vagrant VM (`vgrant_kvmi`), run Libvmi from there -> Introspected guest (`winxp`, installed by default)

**Comment by pranto47** [comment]
In introspected guest, it works.
Thanks for your answer.
