### ISSUE TITLE
Failed to access introspected VM from vagrant VM

### ISSUE THREAD

**Issue by Tanjim131** [KVM-VMI/kvm-vmi#79]
I followed the vagrant based kvmi setup and installed the kernel. After the kernel was installed, I entered the vagrant VM console using ``vagrant ssh kvmi.`` After that, I tried to access the introspected VM from vagrant console. Following is my attempt:

```
vagrant@ubuntu1604:~$ sudo virsh console ubuntu
setlocale: No such file or directory
Connected to domain ubuntu
Escape character is ^]
```
My question is how can I access the introspected ubuntu VM from the kvmi?

**Comment by Wenzel** [comment]
> vagrant ssh kvmi

`vagrant ssh` is enough, you don't need more args.

> vagrant console

There is no vagrant console, it's just an ssh connexion

> sudo virsh console ubuntu

`virsh` is part of `libvirt` tools, not related to vagrant.

I never used the console command.

> My question is how can I access the introspected ubuntu VM from the kvmi?

Use `virt-manager` on your host, and add a new connexion using the `ip` address of the vagrant VM.

This is described here:
https://github.com/KVM-VMI/kvm-vmi/tree/master/vagrant#note-virt-manager

Go the guest, get the ip address with `ip a`

Go to virt-manager, `File` -> `add connexion`, fill the form, and connect, and start the VM

**Comment by Tanjim131** [comment]
I followed the instructions as you described. First inside the guest, I got the IP address:

![1](https://user-images.githubusercontent.com/32413465/94397294-5b5c8400-0185-11eb-9971-993dac1e8d9d.png)

Then I created a connection with that IP address:

![2](https://user-images.githubusercontent.com/32413465/94397321-69120980-0185-11eb-880f-6a27d603ccd0.png)

Finally, I started the VM. But after starting the VM, it got stuck at the following point:

![3](https://user-images.githubusercontent.com/32413465/94397357-7a5b1600-0185-11eb-8b17-9164f7a16453.png)

I can't get past the ``/dev/sda1:clean`` point. How can I resolve this?

**Comment by mtarral** [comment]
Hi,

did you build that VM yourself, or is it one from the templates availables in the Ansible playbook ?

I never used the Ubuntu packer template, so I can't confirm if it works or not.

Remember that this is executing in nested virtualization, so booting takes more time.
Give it a few minutes, and try to send keyboard sequence (`Send Key`) to switch ttys via virt-manager to see how it responds.
It's an Ubuntu server, so there won't be a graphical UI.

**Comment by Tanjim131** [comment]
I did not build the VM myself and used the ansible playbook template. 

So, looks like I was able to access the tty console following the instructions from this [AskUbuntu](https://askubuntu.com/a/596764) answer:

![image](https://user-images.githubusercontent.com/32413465/94437133-28cf7d00-01bf-11eb-96b0-af583d3cc323.png)

Finally the console looks like this:

![image](https://user-images.githubusercontent.com/32413465/94436893-d68e5c00-01be-11eb-8758-1a1df7c90146.png)

**Comment by mtarral** [comment]
I'm closing this issue, feel free to reopen it.
